import { NextResponse } from "next/server";

// NIC 2008 codes — major categories for India
const NIC_CODES = [
  { code: "0111", desc: "Growing of cereals and other crops", division: "Agriculture" },
  { code: "0112", desc: "Growing of vegetables", division: "Agriculture" },
  { code: "0121", desc: "Growing of grapes", division: "Agriculture" },
  { code: "0130", desc: "Growing of spices, aromatic and pharmaceutical crops", division: "Agriculture" },
  { code: "0141", desc: "Raising of cattle and buffaloes", division: "Agriculture" },
  { code: "0150", desc: "Mixed farming", division: "Agriculture" },
  { code: "1010", desc: "Processing and preserving of meat", division: "Food" },
  { code: "1020", desc: "Processing of fish and seafood", division: "Food" },
  { code: "1030", desc: "Processing of fruits and vegetables", division: "Food" },
  { code: "1040", desc: "Manufacture of vegetable and animal oils and fats", division: "Food" },
  { code: "1050", desc: "Manufacture of dairy products", division: "Food" },
  { code: "1061", desc: "Manufacture of grain mill products", division: "Food" },
  { code: "1071", desc: "Manufacture of bakery products", division: "Food" },
  { code: "1072", desc: "Manufacture of sugar", division: "Food" },
  { code: "1080", desc: "Manufacture of prepared animal feeds", division: "Food" },
  { code: "1101", desc: "Distilling and blending of spirits", division: "Beverages" },
  { code: "1102", desc: "Manufacture of wines", division: "Beverages" },
  { code: "1104", desc: "Manufacture of soft drinks", division: "Beverages" },
  { code: "1200", desc: "Manufacture of tobacco products", division: "Tobacco" },
  { code: "1311", desc: "Preparation and spinning of textile fibres", division: "Textiles" },
  { code: "1312", desc: "Weaving of textiles", division: "Textiles" },
  { code: "1313", desc: "Finishing of textiles", division: "Textiles" },
  { code: "1391", desc: "Manufacture of knitted and crocheted fabrics", division: "Textiles" },
  { code: "1410", desc: "Manufacture of wearing apparel", division: "Apparel" },
  { code: "1420", desc: "Manufacture of articles of fur", division: "Apparel" },
  { code: "1430", desc: "Manufacture of knitted and crocheted apparel", division: "Apparel" },
  { code: "1511", desc: "Preparation of leather and hide", division: "Leather" },
  { code: "1512", desc: "Manufacture of luggage, handbags", division: "Leather" },
  { code: "1520", desc: "Manufacture of footwear", division: "Leather" },
  { code: "1610", desc: "Sawmilling and planing of wood", division: "Wood" },
  { code: "1621", desc: "Manufacture of veneer sheets", division: "Wood" },
  { code: "1622", desc: "Manufacture of builders carpentry and joinery", division: "Wood" },
  { code: "1701", desc: "Manufacture of pulp", division: "Paper" },
  { code: "1702", desc: "Manufacture of corrugated paper and paperboard", division: "Paper" },
  { code: "1811", desc: "Printing", division: "Printing" },
  { code: "1812", desc: "Service activities related to printing", division: "Printing" },
  { code: "1910", desc: "Manufacture of coke oven products", division: "Petroleum" },
  { code: "1920", desc: "Manufacture of refined petroleum products", division: "Petroleum" },
  { code: "2011", desc: "Manufacture of basic chemicals", division: "Chemicals" },
  { code: "2012", desc: "Manufacture of fertilisers and nitrogen compounds", division: "Chemicals" },
  { code: "2013", desc: "Manufacture of plastics in primary forms", division: "Chemicals" },
  { code: "2014", desc: "Manufacture of other basic organic chemicals", division: "Chemicals" },
  { code: "2021", desc: "Manufacture of pesticides", division: "Chemicals" },
  { code: "2022", desc: "Manufacture of paints, varnishes", division: "Chemicals" },
  { code: "2023", desc: "Manufacture of soap and detergents", division: "Chemicals" },
  { code: "2030", desc: "Manufacture of man-made fibres", division: "Chemicals" },
  { code: "2100", desc: "Manufacture of pharmaceuticals and medicinal chemical", division: "Pharma" },
  { code: "2211", desc: "Manufacture of rubber tyres and tubes", division: "Rubber" },
  { code: "2219", desc: "Manufacture of other rubber products", division: "Rubber" },
  { code: "2220", desc: "Manufacture of plastics products", division: "Plastics" },
  { code: "2310", desc: "Manufacture of glass and glass products", division: "Non-metallic" },
  { code: "2391", desc: "Manufacture of refractory products", division: "Non-metallic" },
  { code: "2394", desc: "Manufacture of cement, lime and plaster", division: "Non-metallic" },
  { code: "2395", desc: "Manufacture of articles of concrete", division: "Non-metallic" },
  { code: "2410", desc: "Manufacture of basic iron and steel", division: "Metals" },
  { code: "2420", desc: "Manufacture of basic precious and other non-ferrous metals", division: "Metals" },
  { code: "2511", desc: "Manufacture of structural metal products", division: "Metal Products" },
  { code: "2512", desc: "Manufacture of tanks, reservoirs", division: "Metal Products" },
  { code: "2591", desc: "Forging, pressing, stamping of metal", division: "Metal Products" },
  { code: "2610", desc: "Manufacture of electronic components", division: "Electronics" },
  { code: "2620", desc: "Manufacture of computers and peripheral equipment", division: "Electronics" },
  { code: "2630", desc: "Manufacture of communication equipment", division: "Electronics" },
  { code: "2640", desc: "Manufacture of consumer electronics", division: "Electronics" },
  { code: "2710", desc: "Manufacture of electric motors, generators", division: "Electrical" },
  { code: "2720", desc: "Manufacture of batteries and accumulators", division: "Electrical" },
  { code: "2731", desc: "Manufacture of fibre optic cables", division: "Electrical" },
  { code: "2740", desc: "Manufacture of electric lighting equipment", division: "Electrical" },
  { code: "2750", desc: "Manufacture of domestic appliances", division: "Electrical" },
  { code: "2811", desc: "Manufacture of engines and turbines", division: "Machinery" },
  { code: "2812", desc: "Manufacture of fluid power equipment", division: "Machinery" },
  { code: "2910", desc: "Manufacture of motor vehicles", division: "Vehicles" },
  { code: "2920", desc: "Manufacture of automobile bodies", division: "Vehicles" },
  { code: "2930", desc: "Manufacture of parts for motor vehicles", division: "Vehicles" },
  { code: "3011", desc: "Building of ships and floating structures", division: "Transport Equip" },
  { code: "3030", desc: "Manufacture of air and spacecraft", division: "Transport Equip" },
  { code: "3091", desc: "Manufacture of motorcycles", division: "Transport Equip" },
  { code: "3100", desc: "Manufacture of furniture", division: "Furniture" },
  { code: "3211", desc: "Manufacture of jewellery and related articles", division: "Other Mfg" },
  { code: "3220", desc: "Manufacture of musical instruments", division: "Other Mfg" },
  { code: "3290", desc: "Other manufacturing n.e.c.", division: "Other Mfg" },
  { code: "3510", desc: "Electric power generation, transmission and distribution", division: "Utilities" },
  { code: "3520", desc: "Manufacture of gas; distribution of gaseous fuels", division: "Utilities" },
  { code: "3530", desc: "Steam and air conditioning supply", division: "Utilities" },
  { code: "3600", desc: "Water collection, treatment and supply", division: "Water" },
  { code: "3811", desc: "Collection of non-hazardous waste", division: "Waste Mgmt" },
  { code: "4100", desc: "Construction of buildings", division: "Construction" },
  { code: "4210", desc: "Construction of roads and railways", division: "Construction" },
  { code: "4220", desc: "Construction of utility projects", division: "Construction" },
  { code: "4510", desc: "Sale of motor vehicles", division: "Trade" },
  { code: "4520", desc: "Maintenance and repair of motor vehicles", division: "Trade" },
  { code: "4530", desc: "Sale of motor vehicle parts and accessories", division: "Trade" },
  { code: "4610", desc: "Wholesale on a fee or contract basis", division: "Wholesale" },
  { code: "4620", desc: "Wholesale of agricultural raw materials", division: "Wholesale" },
  { code: "4630", desc: "Wholesale of food, beverages and tobacco", division: "Wholesale" },
  { code: "4649", desc: "Wholesale of other household goods", division: "Wholesale" },
  { code: "4661", desc: "Wholesale of solid, liquid and gaseous fuels", division: "Wholesale" },
  { code: "4711", desc: "Retail sale in non-specialised stores - food", division: "Retail" },
  { code: "4719", desc: "Other retail sale in non-specialised stores", division: "Retail" },
  { code: "4721", desc: "Retail sale of food in specialised stores", division: "Retail" },
  { code: "4731", desc: "Retail sale of automotive fuel", division: "Retail" },
  { code: "4741", desc: "Retail sale of computers and software", division: "Retail" },
  { code: "4751", desc: "Retail sale of textiles", division: "Retail" },
  { code: "4761", desc: "Retail sale of books, newspapers", division: "Retail" },
  { code: "4771", desc: "Retail sale of clothing", division: "Retail" },
  { code: "4911", desc: "Passenger rail transport", division: "Transport" },
  { code: "4921", desc: "Urban and suburban passenger land transport", division: "Transport" },
  { code: "4923", desc: "Freight transport by road", division: "Transport" },
  { code: "5011", desc: "Sea and coastal passenger water transport", division: "Transport" },
  { code: "5110", desc: "Passenger air transport", division: "Transport" },
  { code: "5120", desc: "Freight air transport", division: "Transport" },
  { code: "5210", desc: "Warehousing and storage", division: "Storage" },
  { code: "5221", desc: "Service activities incidental to land transportation", division: "Transport Aux" },
  { code: "5510", desc: "Short term accommodation activities - hotels", division: "Hotels" },
  { code: "5520", desc: "Camping grounds and caravan parks", division: "Hotels" },
  { code: "5610", desc: "Restaurants and mobile food service", division: "Food Service" },
  { code: "5620", desc: "Event catering", division: "Food Service" },
  { code: "5811", desc: "Book publishing", division: "Publishing" },
  { code: "5813", desc: "Publishing of newspapers, journals", division: "Publishing" },
  { code: "5820", desc: "Software publishing", division: "IT" },
  { code: "6010", desc: "Radio broadcasting", division: "Broadcasting" },
  { code: "6020", desc: "Television programming and broadcasting", division: "Broadcasting" },
  { code: "6110", desc: "Wired telecommunications activities", division: "Telecom" },
  { code: "6120", desc: "Wireless telecommunications activities", division: "Telecom" },
  { code: "6130", desc: "Satellite telecommunications activities", division: "Telecom" },
  { code: "6190", desc: "Other telecommunications activities", division: "Telecom" },
  { code: "6201", desc: "Computer programming activities", division: "IT" },
  { code: "6202", desc: "Computer consultancy activities", division: "IT" },
  { code: "6209", desc: "Other information technology service activities", division: "IT" },
  { code: "6311", desc: "Data processing, hosting and related activities", division: "IT" },
  { code: "6312", desc: "Web portals", division: "IT" },
  { code: "6391", desc: "News agency activities", division: "IT" },
  { code: "6411", desc: "Central banking", division: "Finance" },
  { code: "6419", desc: "Other monetary intermediation", division: "Finance" },
  { code: "6420", desc: "Activities of holding companies", division: "Finance" },
  { code: "6430", desc: "Trusts, funds and similar financial entities", division: "Finance" },
  { code: "6491", desc: "Financial leasing", division: "Finance" },
  { code: "6499", desc: "Other financial service activities n.e.c.", division: "Finance" },
  { code: "6511", desc: "Life insurance", division: "Insurance" },
  { code: "6512", desc: "Non-life insurance", division: "Insurance" },
  { code: "6520", desc: "Reinsurance", division: "Insurance" },
  { code: "6530", desc: "Pension funding", division: "Insurance" },
  { code: "6611", desc: "Administration of financial markets", division: "Finance Aux" },
  { code: "6612", desc: "Security and commodity contracts brokerage", division: "Finance Aux" },
  { code: "6619", desc: "Other activities auxiliary to financial services", division: "Finance Aux" },
  { code: "6810", desc: "Real estate activities with own or leased property", division: "Real Estate" },
  { code: "6820", desc: "Real estate activities on a fee or contract basis", division: "Real Estate" },
  { code: "6910", desc: "Legal activities", division: "Professional" },
  { code: "6920", desc: "Accounting, bookkeeping and auditing activities", division: "Professional" },
  { code: "7010", desc: "Activities of head offices", division: "Professional" },
  { code: "7020", desc: "Management consultancy activities", division: "Professional" },
  { code: "7110", desc: "Architectural and engineering activities", division: "Professional" },
  { code: "7120", desc: "Technical testing and analysis", division: "Professional" },
  { code: "7210", desc: "Research and experimental development on natural sciences", division: "R&D" },
  { code: "7220", desc: "Research and experimental development on social sciences", division: "R&D" },
  { code: "7310", desc: "Advertising", division: "Marketing" },
  { code: "7320", desc: "Market research and public opinion polling", division: "Marketing" },
  { code: "7410", desc: "Specialised design activities", division: "Professional" },
  { code: "7420", desc: "Photographic activities", division: "Professional" },
  { code: "7490", desc: "Other professional, scientific activities n.e.c.", division: "Professional" },
  { code: "7500", desc: "Veterinary activities", division: "Veterinary" },
  { code: "7710", desc: "Renting and leasing of motor vehicles", division: "Rental" },
  { code: "7730", desc: "Renting and leasing of other machinery", division: "Rental" },
  { code: "7740", desc: "Leasing of intellectual property", division: "Rental" },
  { code: "7810", desc: "Activities of employment placement agencies", division: "Employment" },
  { code: "7820", desc: "Temporary employment agency activities", division: "Employment" },
  { code: "7830", desc: "Human resources provision", division: "Employment" },
  { code: "7911", desc: "Travel agency activities", division: "Travel" },
  { code: "7912", desc: "Tour operator activities", division: "Travel" },
  { code: "8010", desc: "Private security activities", division: "Security" },
  { code: "8020", desc: "Security systems service activities", division: "Security" },
  { code: "8110", desc: "Combined facilities support activities", division: "Facilities" },
  { code: "8121", desc: "General cleaning of buildings", division: "Facilities" },
  { code: "8130", desc: "Landscape service activities", division: "Facilities" },
  { code: "8211", desc: "Office administrative service activities", division: "Admin" },
  { code: "8219", desc: "Photocopying, document preparation", division: "Admin" },
  { code: "8220", desc: "Activities of call centres", division: "Admin" },
  { code: "8230", desc: "Organisation of conventions and trade shows", division: "Admin" },
  { code: "8411", desc: "General public administration activities", division: "Government" },
  { code: "8423", desc: "Justice and judicial activities", division: "Government" },
  { code: "8424", desc: "Public order and safety activities", division: "Government" },
  { code: "8425", desc: "Fire service activities", division: "Government" },
  { code: "8430", desc: "Compulsory social security activities", division: "Government" },
  { code: "8510", desc: "Pre-primary education", division: "Education" },
  { code: "8520", desc: "Primary education", division: "Education" },
  { code: "8531", desc: "General secondary education", division: "Education" },
  { code: "8532", desc: "Technical and vocational secondary education", division: "Education" },
  { code: "8541", desc: "Post-secondary non-tertiary education", division: "Education" },
  { code: "8542", desc: "Tertiary education", division: "Education" },
  { code: "8550", desc: "Other education", division: "Education" },
  { code: "8610", desc: "Hospital activities", division: "Health" },
  { code: "8620", desc: "Medical and dental practice activities", division: "Health" },
  { code: "8690", desc: "Other human health activities", division: "Health" },
  { code: "8710", desc: "Residential nursing care facilities", division: "Health" },
  { code: "8720", desc: "Residential care activities for mental retardation", division: "Health" },
  { code: "8730", desc: "Residential care activities for the elderly", division: "Health" },
  { code: "8810", desc: "Social work activities without accommodation for elderly", division: "Social" },
  { code: "9000", desc: "Creative, arts and entertainment activities", division: "Arts" },
  { code: "9101", desc: "Library and archives activities", division: "Arts" },
  { code: "9102", desc: "Museums activities", division: "Arts" },
  { code: "9200", desc: "Gambling and betting activities", division: "Gambling" },
  { code: "9311", desc: "Operation of sports facilities", division: "Sports" },
  { code: "9312", desc: "Activities of sports clubs", division: "Sports" },
  { code: "9319", desc: "Other sports activities", division: "Sports" },
  { code: "9321", desc: "Activities of amusement parks", division: "Entertainment" },
  { code: "9329", desc: "Other amusement and recreation activities", division: "Entertainment" },
  { code: "9411", desc: "Activities of business and employers membership organisations", division: "Membership" },
  { code: "9412", desc: "Activities of professional membership organisations", division: "Membership" },
  { code: "9420", desc: "Activities of trade unions", division: "Membership" },
  { code: "9491", desc: "Activities of religious organisations", division: "Religion" },
  { code: "9492", desc: "Activities of political organisations", division: "Political" },
  { code: "9499", desc: "Activities of other membership organisations n.e.c.", division: "Membership" },
  { code: "9511", desc: "Repair of computers and peripheral equipment", division: "Repair" },
  { code: "9512", desc: "Repair of communication equipment", division: "Repair" },
  { code: "9521", desc: "Repair of consumer electronics", division: "Repair" },
  { code: "9601", desc: "Washing and dry-cleaning of textile", division: "Personal Svcs" },
  { code: "9602", desc: "Hairdressing and other beauty treatment", division: "Personal Svcs" },
  { code: "9603", desc: "Funeral and related activities", division: "Personal Svcs" },
  { code: "9609", desc: "Other personal service activities n.e.c.", division: "Personal Svcs" },
  { code: "9700", desc: "Activities of households as employers", division: "Households" },
];

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const q = searchParams.get("q")?.toLowerCase().trim() || "";
  const division = searchParams.get("division") || "";

  if (!q && !division) {
    const divisions = [...new Set(NIC_CODES.map(n => n.division))].sort();
    return NextResponse.json({ divisions, total: NIC_CODES.length });
  }

  let results = NIC_CODES;
  if (division) results = results.filter(n => n.division === division);
  if (q) results = results.filter(n =>
    n.code.includes(q) || n.desc.toLowerCase().includes(q) || n.division.toLowerCase().includes(q)
  );

  return NextResponse.json({ results: results.slice(0, 50), total: results.length });
}
