export const countries = [
  {
    code: 'IN',
    slug: 'india',
    name: 'India',
    flag: '🇮🇳',
    badge: 'Live',
    description: 'GST, TDS, ITR, legal practice workflows',
    signinUrl: 'https://in.klaro.services/signin',
    signupUrl: 'https://in.klaro.services/signup',
  },
  {
    code: 'AE',
    slug: 'uae',
    name: 'UAE',
    flag: '🇦🇪',
    badge: 'Coming soon',
    description: 'VAT, corporate tax, business compliance',
    signinUrl: 'https://ae.klaro.services/signin',
    signupUrl: 'https://ae.klaro.services/signup',
  },
  {
    code: 'US',
    slug: 'us',
    name: 'United States',
    flag: '🇺🇸',
    badge: 'Coming soon',
    description: 'Tax, legal operations, practice management',
    signinUrl: 'https://us.klaro.services/signin',
    signupUrl: 'https://us.klaro.services/signup',
  },
  {
    code: 'EU',
    slug: 'eu',
    name: 'European Union',
    flag: '🇪��',
    badge: 'Coming soon',
    description: 'VAT, privacy, cross-border workflows',
    signinUrl: 'https://eu.klaro.services/signin',
    signupUrl: 'https://eu.klaro.services/signup',
  },
] as const;
